# Host: 192.168.187.200  (Version: 5.6.19)
# Date: 2014-08-26 12:12:11
# Generator: MySQL-Front 5.3  (Build 4.136)

/* SET NAMES utf8 */;
USE sphinx-console;

DELETE from SEARCH_QUERY_RESULT;
DELETE from SEARCH_QUERY;
DELETE from SNIPPET_CONFIGURATION_FIELD;
DELETE from SNIPPET_CONFIGURATION;
DELETE from COMMAND;
DELETE from DISTRIBUTED_COLLECTION_AGENT;
DELETE from DISTRIBUTED_COLLECTION_NODE;
DELETE from ACTIVITY_LOG;
DELETE FROM ADMIN_PROCESS;
DELETE FROM DELTA;
DELETE FROM SPHINX_PROCESS;
DELETE FROM SERVER;
DELETE FROM CONFIGURATION_FIELDS;
DELETE FROM FIELD_MAPPING;
DELETE FROM CONFIGURATION;
DELETE FROM EXTERNAL_ACTION;
DELETE from DATASOURCE;
DELETE FROM CONFIGURATION_TEMPLATE;
DELETE FROM DELETE_SCHEME;
DELETE FROM PARTITION_TABLE;
DELETE FROM REPLICA;
DELETE FROM SCHEDULED_TASK;
DELETE FROM COLLECTION;

